namespace: mafia
backend:
  image: <%PROJECT__68553af9-489f-4810-8406-d20d926ab630__master%>
  replicaCount: 1
  port: 3000
  targetPort: 3000
ui:
  image: <%PROJECT__495b5cd4-50f5-4539-870d-c71557ad6075__master%>
  replicaCount: 1
  port: 80
  targetPort: 80
ingress:
  nginxEnabled: false
  traefikEnabled: true
  host: mafia.rhythm.relizahub.com