on: [push]

name: Obtain version from Reliza and register new update there

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      RELIZA_API_ID: ${{ secrets.RELIZA_API_ID }}
      RELIZA_API_KEY: ${{ secrets.RELIZA_API_KEY }}
      RELIZA_HUB_URI: ${{ secrets.RELIZA_HUB_URI }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate version and stream version to Reliza Hub
        run: |
          # get version
          docker pull relizaio/reliza-cli
          echo -u $RELIZA_HUB_URI  -k $RELIZA_API_KEY -i $RELIZA_API_ID -b $GITHUB_REF --metadata GitHub
          docker run --rm relizaio/reliza-cli getversion -u $RELIZA_HUB_URI -k $RELIZA_API_KEY -i $RELIZA_API_ID -b $GITHUB_REF --metadata GitHub > full_version_output 2>&1
          # show reliza command output in case there is error
          cat full_version_output
          cat full_version_output | jq -r ".version" > version
          vvar=$(cat version)
          # Construct Reliza command to stream version to reliza
          echo -n "--artid github.com/$GITHUB_REPOSITORY " >> reliza_command
          echo -n "--artbuildid github$GITHUB_ACTION$GITHUB_SHA " >> reliza_command
          echo -n "--artbuilduri https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID " >> reliza_command
          echo -n "--artcimeta GitHub Actions " >> reliza_command
          echo -n "--arttype file " >> reliza_command
          echo -n "--artdigests sha1:$GITHUB_SHA " >> reliza_command
          echo -n "-b $GITHUB_REF --vcstype git --commit $GITHUB_SHA  -u ${{ secrets.RELIZA_HUB_URI }} -k ${{ secrets.RELIZA_API_KEY }} -i ${{ secrets.RELIZA_API_ID }} --vcsuri github.com/$GITHUB_REPOSITORY \
              -v $vvar" >> reliza_command
          cat reliza_command
          # send version to reliza
          docker run --rm relizaio/reliza-cli addrelease $(cat reliza_command)